 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/kero-demo-image', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/kero-demo-image']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'kero-demo-image'
   - '--image'
   - 'gcr.io/$PROJECT_ID/kero-demo-image'
   - '--region'
   - 'us-east1'
 images:
 - 'gcr.io/$PROJECT_ID/kero-demo-image'
